language: android
jdk: oraclejdk8

android:
  components:
    - extra-android-m2repository
    - build-tools-21.1.2
    - android-19
    - sys-img-armeabi-v7a-android-19
env:
  - TESTS=dis-client

before_script:
  - '[ "${TESTS}" = "dis-client" ] && dis-client/ci/script/before.sh || true'

script:
  - '[ "${TESTS}" = "dis-client" ] && (cd dis-client && ./gradlew test connectedAndroidTest) || true'
