language: android
jdk: oraclejdk8

android:
  components:
    - extra-android-m2repository
    - build-tools-21.1.2
    - android-19
    - sys-img-armeabi-v7a-android-19
env:
  - COMPONENT=dis-client
  - COMPONENT=dis-server
  - COMPONENT=dis-ingest

before_script:
  - '[ "${COMPONENT}" = "dis-client" ] && dis-client/ci/script/before.sh || true'

script:
  - '[ "${COMPONENT}" = "dis-client" ] && (cd dis-client && ./gradlew test connectedAndroidTest) || true'
  - '[ "${COMPONENT}" = "dis-server" ] && (cd dis-server && ./gradlew test) || true'
  - '[ "${COMPONENT}" = "dis-ingest" ] && (cd dis-ingest && ./gradlew test) || true'
