resources:
  - name: github
    type: git
    source:
      uri: https://github.com/pivotal/dis-android.git
      branch: master

  - name: hockey
    type: hockey

jobs:
  - name: test
    plan:
      - get: github
        trigger: true
      - task: test
        file: github/concourse/tasks/test.yml
  - name: package
    plan:
      - get: github
        trigger: true
        passed: [test]
      - task: package
        file: github/concourse/task/package.yml
      - put: hockey
